---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-control-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edc-control-plane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "edc-control-plane.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "edc-control-plane.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: default
              containerPort: {{ .Values.edc.endpoints.default.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.edc.endpoints.management.port }}
              protocol: TCP
            - name: validation
              containerPort: {{ .Values.edc.endpoints.validation.port }}
              protocol: TCP
            - name: control
              containerPort: {{ .Values.edc.endpoints.control.port }}
              protocol: TCP
            - name: ids
              containerPort: {{ .Values.edc.endpoints.ids.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.edc.endpoints.metrics.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/liveness
              port: default
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/readiness
              port: default
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/startup
              port: default
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configuration
              mountPath: /app/configuration.properties
              subPath: configuration.properties
            - name: configuration
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: configuration
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: configuration
          configMap:
            name: {{ .Chart.Name }}
            items:
              - key: configuration.properties
                path: configuration.properties
              - key: opentelemetry.properties
                path: opentelemetry.properties
              - key: logging.properties
                path: logging.properties
