---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "digital-twin-registry.labels" . | nindent 4 }}
data:
    SPRING_DATASOURCE_DRIVERCLASSNAME: {{ .Values.dataSource.driverClassName }}
    SPRING_SQL_INIT_PLATFORM: {{ .Values.dataSource.sqlInitPlatform }}
