---
{{ if .Values.install.digitalTwin }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: digital-twin-registry-database-pv
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    type: local
    app: postgres
    db: digital-twin-registry
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/digitalTwin"

{{ end }}