---
{{ if .Values.install.edc.provider }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.edc.provider.database.secret.name  | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: Opaque
stringData:
  password: {{ .Values.config.edc.provider.database.password | toString | quote }}
  postgres-password: {{ .Values.config.edc.provider.database.postgres.password | toString | quote }}

{{ end }}