---
{{ if .Values.install.edc.provider }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: edc-provider-database-pv
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    type: local
    app: postgres
    db: edc-provider
  annotations:
    "helm.sh/resource-policy": keep    
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/edc_provider"

{{ end }}