---
{{ if .Values.install.edc.consumer }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: edc-consumer-database-pv
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    type: local
    app: postgres
    db: edc-consumer
  annotations:
    "helm.sh/resource-policy": keep    
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/edc_consumer"

{{ end }}