{{- if .Values.irs.grafana.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.grafana.secret.name  | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: Opaque
stringData:
  grafanaUser: {{ .Values.irs.grafana.username | toString | quote }}
  grafanaPassword: {{ .Values.irs.grafana.password | toString | quote }}

{{- end }}