---
{{- if .Values.irs.grafana.enabled -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app: grafana
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: standard
  volumeName: grafana-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

{{- end }}